### ISSUE TITLE
Tween execution when the game is paused

### ISSUE THREAD

**Issue by gamedevserj** [Guillemsc/GTweensGodot#13]
First of all I wanted to thank you for the creation of this library, it is awesome!

Currently the extension relies on ```_Process``` method that is called by GodotGTweensContextNode.cs to update tweens. 
Leaving the script as is would mean that when pausing the game no tween would be updated. 
Which means that using it for fading menus in/out is not possible, unless we add ```_Ready``` method where we set ```ProcessMode = ProcessModeEnum.Always;```
However doing so would mean that any tween that controls game objects (moving platforms etc.) would also be executed even if the game is paused.
My suggestion is to have two nodes (and I'm guessing two contexts) that have different process modes and add an option for tween to set whether it should be updated when the game is paused or not. 

Although I guess it goes against the issue https://github.com/Guillemsc/GTweensGodot/issues/5, because it would not help simplify installation.

**Comment by gamedevserj** [comment]
Hey @Guillemsc thanks for the quick reply!
Yeah, it looks like it should fix it, and hopefully any other issues that are not apparent now :)

**Comment by Guillemsc** [comment]
Cool, sounds good then, I'll work on the feature and release a new version as soon as I can.
Thanks for raising this 👍

**Comment by Guillemsc** [comment]
@gamedevserj would It also make sense to, instead of having ` void Play(bool pausable = true)`, have `Play` and `PlayUnpausable`? 
This way I don't have to add as many parameters to all Play variant methods. I think it would lead to a cleaner API.

**Comment by gamedevserj** [comment]
@Guillemsc honestly, I don't know. 
When I was using Unity there is an asset called DOTween where they use ```.SetUpdate``` with enum type where it can be set as independent of TimeScale.
I think having two separate methods is fine in this case.

**Comment by Guillemsc** [comment]
Yeah, but in this case Unity and Godot work differently in the sense that _Process is not even called when it's paused, where in Unity pausing is done by setting TimeScale to 0, which makes things easier.
I'll go with two separate methods for now then, thanks.

**Comment by Guillemsc** [comment]
A new [version](https://github.com/Guillemsc/GTweensGodot/releases/tag/v5.0.0) has been released with this implemented (nuget and asset library still on review).
If you encounter any issue or have any other suggestion, don't hesitate on opening a new issue 😀.

**Comment by gamedevserj** [comment]
@Guillemsc awesome, thanks a lot!
