### ISSUE TITLE
Issue with tweening godot vectors

### ISSUE THREAD

**Issue by gamedevserj** [Guillemsc/GTweensGodot#19]
[Generic tweening](https://github.com/Guillemsc/GTweensGodot#generic-tweening) doesn't work with Godot's vectors
 ```
Vector3 test;
 GTween t = GTweenGodotExtensions.Tween(test, x => test = x, Vector3.One, 1f);
```
The error is [CS0029](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0029?f1url=%3FappId%3Droslyn%26k%3Dk(CS0029)) where it says that I can't  implicitly convert Godot.Vector2I to Godot.Vector3, although Vector2I is not used in my code at all.

Hovering over parameters in tween shows that both test and x are Vector3

Generic tweening of default c# values seems to be working without a problem

**Comment by Guillemsc** [comment]
Hey, thanks for raising this, I'll investigate and fix.

**Comment by Guillemsc** [comment]
Hey @gamedevserj, sorry for the delay!
The getter (first parameter of the Tween function) is an action, so you need to use it like this:
```csharp
Vector3 test = Vector3.Zero; // You need to initialize this or there is a compile error
GTween t = GTweenGodotExtensions.Tween(() => test, x => test = x, Vector3.One, 1f);
```
I'll close this, but don't hesitate to open another issue if I missed something, or it's still not working for you.

**Comment by gamedevserj** [comment]
Hey @Guillemsc thanks! 
Can't believe I didn't notice it :facepalm:
And no worries about the time!
