### ISSUE TITLE
Issues with Loops

### ISSUE THREAD

**Issue by maxloy** [Guillemsc/GTweensGodot#7]
Setting any positive value as the parameter for the SetLoops function loops forever, no matter what the value is. Additionally, setting the enum to CurrentValues does not work as expected (stops looping entirely, presumably a related issue to the first point).

Either the integer parameter should be changed to a bool or it should set the maximum number of loops, with -1 being "loop forever".

I would also suggest changing the name of the CurrentValues enum to either YoYo or PingPong for clarity.

EDIT: In retrospect, I've only actually tested this with Position tweens. Worth double checking other implementations if there are any.

**Comment by Guillemsc** [comment]
Fix will ve avaliable on next v0.3 version
